---
title: "Call for papers"
subtitle: "Women in Logic 2026"
---

Topics of interest include but are not limited to: automata theory, automated deduction, categorical models and logics, concurrency and distributed computation, constraint programming, constructive mathematics, database theory, decision procedures, description logics, domain theory, finite model theory, formal aspects of program analysis, formal methods, foundations of computability, games and logic, higher-order logic, lambda and combinatory calculi, linear logic, logic in artificial intelligence, logic programming, logical aspects of bioinformatics, logical aspects of computational complexity, logical aspects of quantum computation, logical frameworks, logics of programs, modal and temporal logics, model checking, probabilistic systems, process calculi, programming language semantics, proof theory, real-time systems, reasoning about security and privacy, rewriting, type systems and type theory, and verification.


### Important dates

- Abstract submission deadline: ~~May 7, 2026~~ May 10, 2026 
- Abstract notification: ~~May 15, 2026~~ May 18, 2026
- Grant application deadline: ~~May 17, 2026~~ May 20, 2026
- Grant notification: ~~May 19, 2026~~ May 22, 2026
- Early registration: June 1st, 2026
- Contribution for Informal Proceedings: June 25, 2026
- Workshop: 24-25 July 2026

### Accepted contributions

- A Proof-Theoretic Treatment of Incorrect/Incomplete Proofs via Hilbert’s Epsilon Calculus by Mariami Gamsakhurdia 
- Toward Provably Defeasible Machine Learning by Ruvarashe Madzime 
- Axiomatising asynchronous announcements in dynamic epistemic logic by Clara Lerouvillois 
- Double Negation Elimination and the Multiple Succedent Structure of LK by Nox Cowie
- Tackling the Multi-Batching Problem: An Answer Set Programming Approach for Industrial Logistics by Racquel Nina Dennison 
- A Truthmaker Semantics for Positive Free Logic by Ragna Talea Oeynhausen
- Reflexivity and the Blocking of Semantic Paradox by Shuwen Wu 
- Fuzzifying Derivatives of Regular Expressions by Mariam Katamashvili
- Quad Algebras and a 4-Valued Non-Classical Logic by Arun Kumar, Bisham Dewan, Neha Gaur
- Eternal Relaxed Vertex Cover on Threshold Graphs by Ankita Kumari
- Social Network Aggregation Beyond Preservation by Yutong Yi 
- When Queries Decompose: A Lattice-Theoretic Perspective on Incomplete Information by Eugenia Ternovska 
- Formal verification of security protocols with certification by R Ramanujam, Vaishnavi Sundararajan, S P Suresh 
- Schemata, Cyclic Proofs and Herbrand Systems by Alexander Leitsch leit,  Anela Lolic, Stella Mahler 
- On the hyperintensionality of ignorance by Ekaterina Kubyshkina, Mattia Petrolo 
- Answer Set Programming goes to School by Racquel Dennison, Emmanuelle Dietz, Hanna Philipp
- Free sets, thin and Rainbows for Barriers by Lorenzo Carlucci, Oriola Gjetaj
- Logical Modeling of Belief Polarization by Mina Young Pedersen, Sonja Smets
- A Decision Algorithm for the CL15 Fragment of Computability Logic by Stella Spadoni 
- An Intercalation Calculus with Partial Proof Terms by Ana Catarina Sousa 
- Verifiable Higher-Order Automated Reasoning by Melanie Taprogge 
- Improving Model Finding in Quantified Modal Logics by Happy Khairunnisa Sariyanto 
- Paradoxes and Proofs with Programs by Paulette Koronkevich, William J. Bowman 
- Growing HOLMS: Grzegorczyk Logic and Experiments with Translations in HOL Light by Antonella Bilotta, Cosimo Perini Brogi, Marco Maggesi
- Argumentation Based Dialogue Games for Deontic Explanations with Uncertainty by Isabella Cissell 
- Quantum Coherence Spaces Revisited: A von Neumann (Co)Algebraic Approach by Thea Li, Vladimir Zamdzhiev 
- Discourse analysis of mathematical texts by Gwenaelle Leon 
- Structural Dynamic Proof Theory for Public Announcement Logic by Clara Lerouvillois
- Recovering Suppressed Entailments in OWL 2 DL via Two-Phase Reasoning by Giulia Biagioni 
- Definability in Counting Logic by Sandra Kiefer

### Submissions

Abstracts should be written in English (max. 2 pages excluding references), and prepared using the [EasyChair style](https://easychair.org/publications/for_authors). The abstracts should be uploaded to the [WiL 2026 FLoC page](https://submissions.floc26.org/wil/paper/new) as a PDF file before the submission deadline on **May 10, 2026**, anywhere on Earth.


### Grants

A limited number of travel grants is available for students/young researchers who would not otherwise have resources to attend WiL, and whose attendance would benefit both the applicant and the event. We expect to be able to help with registration/local/travel expenses. Applicants should note that grants are limited, and that costs in excess of the grant will not be reimbursed.

Grants will be awarded to (co-)authors of accepted papers, based on the grant committee's assessment of the applicant's genuine financial need, the potential benefit to the applicant's education and research, and the potential benefit to WiL.

Applications should be sent by **May 20, 2026** via [this form](https://forms.gle/eEMKbp18en8ma7pj6). The award notification date is May 22, 2026.

The grants will be presented at the conferences; in case a grantee does not attend, the chairs may transfer the grant to another student or give no award.

The grants are kindly offered by ACM SIGLOG, Jane Street, VeTSS, Microsoft and Topos Institute.
