---
title: "Special Issue"
subtitle: "JLC Special Issue – 10 Years of the Women in Logic Workshop"
---

We are pleased to invite submissions to the [Journal of Logic and Computation](https://academic.oup.com/logcom) Special Issue on 10 Years of the Women in Logic Workshop.

This special issue celebrates the 10th anniversary of the Women in Logic Workshop and aims to highlight a decade of contributions by women to the development of logic and its applications. It will showcase both established and emerging voices in the community, marking an important milestone in ongoing efforts to increase visibility, representation, and opportunities for women in logic.

We warmly encourage submissions from researchers across all areas of logic, reflecting the breadth, diversity, and continued growth of this vibrant community.

### Submission

- Submissions should be written in English (maximum 25 pages including references and appendices) and prepared using the template available here: [Template Download](https://liveuclac-my.sharepoint.com/:u:/g/personal/ucacepi_ucl_ac_uk/IQD_SoT64LQ5R6IBR2wl4etYAff9QV-Oc52MLzl_IBh713k?e=gSKZsH) 
- The first author must be a female researcher or a researcher identifying as female.
- The PDFs of the submissions should be sent via e-mail to Jane Spurr <jane@janespurr.net> with "JLC Submission - WiL10" in the subject line by 15 August 2026 (Anywhere on Earth).
- Submissions must present original, unpublished work. 
- All submissions will be subject to the standard peer-review process of the Journal of Logic and Computation and must comply with the journal's [author guidelines](https://academic.oup.com/logcom/pages/General_Instructions).

### Topics of interest 

(include but are not limited to)

- Automata theory 
- Automated deduction
- Categorical models and logics 
- Concurrency and distributed computation
- Constraint programming
- Constructive mathematics
- Database theory
- Decision procedures
- Description logics
- Domain theory
- Finite model theory
- Formal aspects of program analysis
- Formal methods
- Foundations of computability
- Games and logic
- Higher-order logic
- Lambda and combinatory calculi
- Linear logic
- Logic in artificial intelligence
- Logic programming
- Logical aspects of bioinformatics
- Logical aspects of computational complexity
- Logical aspects of quantum computation
- Logical frameworks
- Logics of programs
- Modal and temporal logics
- Model checking
- Probabilistic systems
- Process calculi
- Programming language semantics
- Proof theory
- Real-time systems
- Reasoning about security and privacy
- Rewriting
- Type systems and type theory
- Verification


### Important Date

- Submission deadline: 15 August 2026 (AoE)

### Guest Editors

- Huimin Dong
- Anela Lolic
- Elaine Pimentel


For any enquiries regarding suitability or submission, please feel free to contact the guest editors.
