---
title: "Women in Logic 2026"
subtitle: "Call for papers"
---

Topics of interest include but are not limited to: automata theory, automated deduction, categorical models and logics, concurrency and distributed computation, constraint programming, constructive mathematics, database theory, decision procedures, description logics, domain theory, finite model theory, formal aspects of program analysis, formal methods, foundations of computability, games and logic, higher-order logic, lambda and combinatory calculi, linear logic, logic in artificial intelligence, logic programming, logical aspects of bioinformatics, logical aspects of computational complexity, logical aspects of quantum computation, logical frameworks, logics of programs, modal and temporal logics, model checking, probabilistic systems, process calculi, programming language semantics, proof theory, real-time systems, reasoning about security and privacy, rewriting, type systems and type theory, and verification.


### Important dates

- Abstract submission deadline: May 5, 2026
- Notification: May 15, 2026
- Early registration: TBA
- Contribution for Informal Proceedings: June 25, 2026
- Workshop: 24-25 July 2026


### Submissions

Abstracts should be written in English (1-2 pages), and prepared using the [EasyChair style](https://easychair.org/publications/for_authors). The abstracts should be uploaded to the [WiL 2026 EasyChair page](https://easychair.org/my/conference?conf=wil2026) as a PDF file before the submission deadline on **May 5, 2026**, anywhere on Earth.


### Grants

A limited number of travel grants is available for students/young researchers who would not otherwise have resources to attend WiL, and whose attendance would benefit both the applicant and the event. We expect to be able to help with registration/local/travel expenses. Applicants should note that grants are limited, and that costs in excess of the grant will not be reimbursed.

Grants will be awarded to (co-)authors of accepted papers, based on the grant committee's assessment of the applicant's genuine financial need, the potential benefit to the applicant's education and research, and the potential benefit to WiL.

Applications should be sent by **May 17, 2026** via [this form](https://forms.gle/eEMKbp18en8ma7pj6). The award notification date is May 19, 2026.

The grants will be presented at the conferences; in case a grantee does not attend, the chairs may transfer the grant to another student or give no award.

The grants are kindly offered by ACM SIGLOG, Jane Street, VeTSS, Microsoft and Topos Institute.
