---
title: "Women in Logic Online"
---

<p> [Agata Ciabattoni](https://www.logic.at/staff/agata/) and [Josephine Dik](https://josephinedik.github.io/), 
supported by Andrea Hackl and the Vienna Center for Logic and Algorithms [VCLA](https://www.vcla.at/) are organizing a series of seminars
["Women in Logic ONLINE"](https://www.vcla.at/women-in-logic/).

* Recorded Videos of the talks are available at the VLCA [video channel](https://www.youtube.com/playlist?list=PLdqgJshpd1aWOGdqfrloD69Ev1MSPd0Wg).
they're also slowly added to [Recorded Talks]().

* Talks are expected to happen every two months and you can be notified by subscribing to the mailing list.

<h2> Previous Talks </h2>

<ul> 
<li> [Sara Negri](https://sites.google.com/view/saranegri/home), Università degli Studi di Genova, [Axioms as rules in intuitionistic logic](https://www.youtube.com/watch?v=9AWmizNWqTA), 23 Jun 2025 </li>


<li> [Sonja Smets](https://sites.google.com/site/thesonjasmetssite/), Institute for Logic, Language and Computation, University of Amsterdam, [Logic and Computation of Social Behavior](https://www.youtube.com/watch?v=cMee0vGpMlE), 19 Mar 2025 </li>

<li> [Francesca Poggiolesi](https://sites.google.com/site/poggiolesi/home), CNRS, [Explanatory Proofs: From Logic to Mathematics](https://www.vcla.at/2025/01/women-in-logic-online-talk-with-francesca-poggiolesi/), 24 Jan 2025 </li>

<li> [Laura Kovacs](http://lkovacs.com/), TU - Wien, [Automating Game Reasoning in Blockchain Security](https://www.vcla.at/2024/10/women-in-logic-online-talk-announcement/), 25 Nov 2024 </li>

<li> [Valeria de Paiva](http://vcvpaiva.github.io/), Topos Institute, [Network Mathematics](https://www.vcla.at/2024/02/women-in-logic-online/), 20 March 2024 </li>
</ul>
</p>


